"""Generate TypeScript and JSON Schema from the Pydantic contract source."""
import argparse
import json
from pathlib import Path
from pydantic import BaseModel
from .domain import contracts, runtime
from . import config, ask


def render_type(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "anyOf" in schema:
        return " | ".join(render_type(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        if "prefixItems" in schema:
            return "["+", ".join(render_type(item) for item in schema["prefixItems"])+"]"
        return "Array<"+render_type(schema.get("items", {}))+">"
    if kind == "object":
        if "properties" in schema:
            required = schema.get("required", [])
            return "{ "+"; ".join(json.dumps(key)+("" if key in required else "?")+": "+render_type(value)
                                  for key, value in schema["properties"].items())+" }"
        additional = schema.get("additionalProperties", {})
        return "Record<string, "+(render_type(additional) if isinstance(additional, dict) else "unknown")+">"
    return {"string": "string", "number": "number", "integer": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def generate():
    definitions = {}
    for module in (contracts, runtime, config, ask):
        for name, model in vars(module).items():
            if isinstance(model, type) and issubclass(model, BaseModel) and model is not BaseModel:
                schema = model.model_json_schema()
                definitions.update(schema.pop("$defs", {}))
                definitions[name] = schema
    schema = {"$schema": "https://json-schema.org/draft/2020-12/schema", "$defs": definitions}
    types = "// Generated by python -m app.export_contracts; do not edit.\n"
    types += "\n".join(f"export type {name} = {render_type(value)}" for name, value in sorted(definitions.items()))+"\n"
    return schema, types


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    schema, types = generate()
    outputs = {root/"frontend/src/generated-contracts.ts": types,
               root/"docs/contracts.schema.json": json.dumps(schema, indent=2)+"\n"}
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale generated contract: {path}")
        else:
            path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
