import { useState, type FormEvent } from 'react'
import { request } from './api'
import type { GroundedAnswer, QueryPlan, AnswerClaim } from './generated-contracts'

export default function AskWorkspace() {
  const [question,setQuestion]=useState('Show mud loss evidence in TIPAM'),[formation,setFormation]=useState('TIPAM'),[radius,setRadius]=useState(3),[data,setData]=useState<GroundedAnswer|null>(null),[plan,setPlan]=useState<QueryPlan|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function run(preview=false) {
    setBusy(true);setError('');setData(null);setPlan(null)
    try {
      const input={question,formation,radius_km:radius,active_well_id:localStorage.getItem('nwis-active-well-v1')||'SYN-ACTIVE-01',session_id:localStorage.getItem('nwis-replay-run-v1')||null}
      if(preview)setPlan(await request<QueryPlan>('/api/ask/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}))
      else {const answer=await request<GroundedAnswer>('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});setData(answer);setPlan(answer.plan)}
    } catch(e){setError(e instanceof Error?e.message:'Question unavailable')}finally{setBusy(false)}
  }
  const claims=(title:string,rows:AnswerClaim[])=><section className="content-section"><h2>{title}</h2>{rows.length?rows.map((c,i)=><article className="answer-claim" key={i}><strong>{c.provenance_type}</strong><p>{c.text}</p><p className="muted">Deterministic citation: {c.tool_ids?.join(', ')||'None'} · source spans: {c.source_ids?.join(', ')||'Structured record'}</p></article>):<p>No grounded statement available.</p>}</section>
  return <><section className="content-section" id="question"><h2>Ask a grounded question</h2><p>Local deterministic planner and answer renderer. Core risk calculations stay in the evidence engines. Source quotations are untrusted data, never instructions.</p><form onSubmit={(e:FormEvent)=>{e.preventDefault();void run()}}><label>Question<textarea value={question} maxLength={2000} required onChange={e=>setQuestion(e.target.value)}/></label><div className="filters"><label>Formation<select value={formation} onChange={e=>setFormation(e.target.value)}>{['TIPAM','BARAIL','NAMSANG'].map(f=><option key={f}>{f}</option>)}</select></label><label>Radius (km)<input type="number" min="1" max="100" value={radius} onChange={e=>setRadius(Number(e.target.value))}/></label><button className="button-primary" disabled={busy}>{busy?'Retrieving grounded records…':'Ask NWIS'}</button><button type="button" className="button-secondary" disabled={busy} onClick={()=>void run(true)}>Preview query plan</button></div></form><p>Try: “Historical mud loss mitigations”, “Nearby offsets within 3 km”, “Show formation Tipam”, or “Why is the mud loss alert elevated?”</p>{error&&<p role="alert">{error}</p>}{data&&<p role="status">{data.status} · Numeric verification {data.numeric_verification.verified?'passed':'rejected'} · {data.model_version}</p>}</section>{plan&&<section className="content-section" id="plan"><h2>Question → deterministic operations</h2><p>Intent {plan.intent}; active well {plan.active_well_id}; formation {plan.formation}; risk {plan.risk_type}.</p><p>{plan.tools.join(' → ')||'No tool calls permitted'}</p>{plan.limitation&&<p>{plan.limitation}</p>}<details><summary>Exact structured plan</summary><pre>{JSON.stringify(plan,null,2)}</pre></details></section>}{data&&<>{claims('Facts',data.facts)}{claims('Computed pattern',data.computed_pattern)}{claims('Interpretation',data.interpretation)}<section className="content-section" id="gaps"><h2>Gaps and uncertainty</h2>{data.gaps.map((g,i)=><p key={i}>{g}</p>)}</section><section className="content-section" id="sources"><h2>Sources</h2>{data.sources.map((s,i)=><article className="answer-claim" key={i}><h3>{String(s.title)} · page {String(s.page)}</h3><blockquote>{String(s.text)}</blockquote><p>Review {String(s.review_status)} · source {String(s.id)}</p><a href={`#documents?document=${s.document_id}&page=${s.page}&span=${s.id}`}>Open highlighted source page</a></article>)}<details><summary>Deterministic tool outputs and versions</summary><pre>{JSON.stringify(data.tool_calls,null,2)}</pre></details></section></>}</>
}
