import { useEffect, useRef, useState } from 'react'
import { API_BASE, request } from './api'

type Box={x:number;y:number;width:number;height:number}
type GoldEvent={event_type:string;md_from_m:number|null;formation_id:string|null;source_quote:string}
type Review={reviewer:string;decision:string;annotations:{event_index:number;source_bbox:Box}[]}
type GoldPage={id:string;page:number;scanned:boolean;text:string;events:GoldEvent[];review:Review|null;image_url:string}
type Summary={status:string;page_count:number;reviewed_pages:number;expected_event_boxes:number;completed_event_boxes:number;independent_human_signoff:boolean}
type GoldResponse={summary:Summary;pages:GoldPage[]}
type UsabilitySummary={status:string;participant_count:number;minimum_participants:number;within_20_seconds_and_correct:number;success_rate:number|null;criterion_verified:boolean;criterion:string}
type ExternalStatus={docker_postgis:{status?:string;result?:string};production_assessment:{production_readiness:string;concurrency_result?:string;concurrency?:{requests:number;workers:number;failures:number;p95_ms:number};blockers?:{id:string;status:string;detail:string}[]};field_validation:{status:string;calibration?:{eligible:boolean;minimum:string};limitations?:string[]}}
const blank=():Box=>({x:.08,y:.08,width:.84,height:.08})

export default function IndependentValidation(){
  const [gold,setGold]=useState<GoldResponse|null>(null),[pageIndex,setPageIndex]=useState(0),[reviewer,setReviewer]=useState(''),[attest,setAttest]=useState(false),[boxes,setBoxes]=useState<Box[]>([]),[message,setMessage]=useState('')
  const [study,setStudy]=useState<UsabilitySummary|null>(null),[started,setStarted]=useState<number|null>(null),[participant,setParticipant]=useState(''),[risk,setRisk]=useState(''),[reasonChoice,setReasonChoice]=useState('UNKNOWN'),[reason,setReason]=useState(''),[sourceOpened,setSourceOpened]=useState(false)
  const [external,setExternal]=useState<ExternalStatus|null>(null)
  const startRef=useRef<number|null>(null)
  const load=()=>request<GoldResponse>('/api/validation/gold/pages').then(value=>{setGold(value);const current=value.pages[pageIndex];setBoxes(current?.review?.annotations.map(a=>a.source_bbox)||current?.events.map(blank)||[])})
  useEffect(()=>{load().catch(e=>setMessage(e.message));request<{summary:UsabilitySummary}>('/api/validation/usability').then(v=>setStudy(v.summary)).catch(()=>{});request<ExternalStatus>('/api/validation/external-status').then(setExternal).catch(()=>{})},[])
  const page=gold?.pages[pageIndex]
  const choose=(index:number)=>{if(!gold)return;setPageIndex(index);const next=gold.pages[index];setBoxes(next.review?.annotations.map(a=>a.source_bbox)||next.events.map(blank)||[]);setMessage('')}
  const changeBox=(index:number,key:keyof Box,value:string)=>setBoxes(rows=>rows.map((box,i)=>i===index?{...box,[key]:Math.max(0,Math.min(1,Number(value)))}:box))
  const save=async()=>{if(!page)return;setMessage('Saving…');try{const value=await request<{summary:Summary}>(`/api/validation/gold/pages/${page.id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewer,independent_human_attestation:attest,decision:'ACCEPTED',annotations:boxes.map((source_bbox,event_index)=>({event_index,source_bbox})),comment:''})});setMessage(`Saved ${page.id}. ${value.summary.reviewed_pages}/${value.summary.page_count} pages reviewed.`);await load()}catch(e){setMessage((e as Error).message)}}
  const start=()=>{const now=performance.now();startRef.current=now;setStarted(now);setRisk('');setReason('');setReasonChoice('UNKNOWN');setSourceOpened(false)}
  const submitStudy=async()=>{if(startRef.current==null)return;const elapsed=(performance.now()-startRef.current)/1000;try{const value=await request<{summary:UsabilitySummary}>('/api/validation/usability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({participant_code:participant,independent_human_attestation:attest,elapsed_seconds:elapsed,identified_risk:risk,identified_reason:reason,reason_choice:reasonChoice,opened_source:sourceOpened})});setStudy(value.summary);setStarted(null);setMessage(`Usability response recorded in ${elapsed.toFixed(1)} seconds.`)}catch(e){setMessage((e as Error).message)}}
  return <>
    <section className="content-section" id="gold-review"><h2>Independent gold-set review</h2><p>This workspace records a named human review separately from extractor output. Every expected event requires a normalized page bounding box. No sign-off is inferred from generated labels.</p>{gold&&<><p><strong>{gold.summary.status.replaceAll('_',' ')}</strong> · {gold.summary.reviewed_pages}/{gold.summary.page_count} pages · {gold.summary.completed_event_boxes}/{gold.summary.expected_event_boxes} event boxes.</p><div className="gold-nav"><button className="button-secondary" disabled={pageIndex===0} onClick={()=>choose(pageIndex-1)}>Previous</button><label>Page<select value={pageIndex} onChange={e=>choose(Number(e.target.value))}>{gold.pages.map((p,i)=><option key={p.id} value={i}>{p.id}{p.review?' · reviewed':''}</option>)}</select></label><button className="button-secondary" disabled={pageIndex===gold.pages.length-1} onClick={()=>choose(pageIndex+1)}>Next</button></div>{page&&<div className="gold-grid"><div><div className="gold-image"><img src={`${API_BASE}${page.image_url.replace('/api/','/api/v1/')}`} alt={`Gold reference ${page.id}`}/>{boxes.map((box,i)=><span key={i} className="gold-box" style={{left:`${box.x*100}%`,top:`${box.y*100}%`,width:`${box.width*100}%`,height:`${box.height*100}%`}}>{i+1}</span>)}</div><p>{page.scanned?'Scanned page':'Native-text page'}</p></div><div><h3>{page.id}</h3>{page.events.length===0?<p>Hard-negative page: confirm that no event is present.</p>:page.events.map((event,i)=><fieldset key={i} className="box-editor"><legend>{event.event_type.replaceAll('_',' ')} · {event.md_from_m??'unknown'} m</legend><blockquote>{event.source_quote}</blockquote><div className="box-fields">{(['x','y','width','height'] as (keyof Box)[]).map(key=><label key={key}>{key}<input type="number" min="0" max="1" step="0.001" value={boxes[i]?.[key]??0} onChange={e=>changeBox(i,key,e.target.value)}/></label>)}</div></fieldset>)}<label>Human reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)} placeholder="Name or controlled reviewer ID"/></label><label className="inline-checkbox"><input type="checkbox" checked={attest} onChange={e=>setAttest(e.target.checked)}/> I am a human reviewer independent of the extractor and I inspected this page.</label><button className="button-primary" onClick={save}>Accept page and boxes</button></div></div>}</>}</section>
    <section className="content-section" id="external-readiness"><h2>External readiness gates</h2>{external&&<><div className="table-scroll"><table><thead><tr><th>Gate</th><th>Status</th><th>Evidence</th></tr></thead><tbody><tr><td>Clean Docker / PostgreSQL / PostGIS</td><td>{external.docker_postgis.status||external.docker_postgis.result||'Recorded'}</td><td>Fresh named volumes, migration, spatial path and API smoke</td></tr><tr><td>Production security and concurrency</td><td>{external.production_assessment.production_readiness.replaceAll('_',' ')}</td><td>{external.production_assessment.concurrency?`${external.production_assessment.concurrency.requests} requests / ${external.production_assessment.concurrency.workers} workers; ${external.production_assessment.concurrency.failures} failures; p95 ${external.production_assessment.concurrency.p95_ms} ms`:'Assessment pending'}</td></tr><tr><td>Independent field validation</td><td>{external.field_validation.status.replaceAll('_',' ')}</td><td>{external.field_validation.calibration?.eligible?'Calibration sample eligible':external.field_validation.calibration?.minimum||'External data and review required'}</td></tr></tbody></table></div>{external.production_assessment.blockers?.map(item=><p key={item.id}><strong>{item.status} · {item.id}</strong>: {item.detail}</p>)}</>}</section>
    <section className="content-section" id="usability-study"><h2>20-second comprehension study</h2><p>{study?.criterion}</p><p><strong>{study?.status.replaceAll('_',' ')||'Loading'}</strong> · {study?.participant_count||0}/{study?.minimum_participants||5} independent participants · verified: {study?.criterion_verified?'Yes':'No'}.</p>{started==null?<><label>Participant code<input value={participant} onChange={e=>setParticipant(e.target.value)} placeholder="e.g. P01"/></label><button className="button-primary" onClick={start}>Start timed task</button></>:<div className="timed-task"><p><strong>Task:</strong> Inspect the active Next Interval Brief, then identify the main risk and why it is shown.</p><a href="#brief" target="_blank" rel="noreferrer">Open Next Interval Brief</a><label>Active risk<input value={risk} onChange={e=>setRisk(e.target.value)} placeholder="Risk name"/></label><label>Primary reason<select value={reasonChoice} onChange={e=>setReasonChoice(e.target.value)}><option value="UNKNOWN">Select</option><option value="HISTORICAL_OFFSET_LOSSES_PROJECTED_AHEAD">Historical offset losses project ahead</option><option value="LOW_BATTERY">Low sensor battery</option><option value="WEATHER_FORECAST">Weather forecast</option></select></label><label>Explain in your own words<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="inline-checkbox"><input type="checkbox" checked={sourceOpened} onChange={e=>setSourceOpened(e.target.checked)}/> I opened a source or “Why?” control.</label><button className="button-primary" onClick={submitStudy}>Submit timed response</button></div>}<p role="status">{message}</p></section>
  </>
}

